[project]
name = "bot-privazy-vpn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.3"
dependencies = [
    "aiogram>=3.26.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "sqlalchemy[asyncio]>=2.0.48",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
    "isort>=8.0.1",
    "pre-commit>=4.5.1",
]

[tool.isort]
# isort settings
profile = "black"
line_length = 100
src_paths  = ["bot"]
known_first_party = ["bot", "database", "config"]
known_third_party = ["aiogram", "sqlalchemy", "pydantic", "alembic"]


[tool.black]
# Black settings
line-length = 100
skip-string-normalization = true
include = "./*.py"
extend-exclude = '''
/(\\.venv|\\.git|__pycache__)/
'''
force-exclude = '''
/(\\.venv|\\.git|__pycache__)/
'''

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.mypy]
disable_error_code = ["untyped-decorator"]
disallow_subclassing_any = false
